### PR TITLE
Added RegEx support

### PR DESCRIPTION
**Pull request by josephgeis**
With this addition, you can use RegEx expressions with `--prefix` and `--suffix`.

### CODE REVIEW

**Comment by robertDurst** [comment]
@juniorRubyist thanks for this! This is quite cool and useful! Sorry for the slow response here.

**Comment by robertDurst** [comment]
Merged, however I think it'd be nice if this warning went away:

```
warning: value assigned to `start` is never read
  --> src/main.rs:64:17
   |
64 |         let mut start: std::string::String = "".to_string();
   |                 ^^^^^
   |
   = note: `#[warn(unused_assignments)]` on by default
   = help: maybe it is overwritten before being read?
```

**Comment by josephgeis** [comment]
@robertDurst I’ll look into that warning. I know it has something to do with one or the other start/end values not being used.

**Comment by robertDurst** [comment]
I actually just pushed a change last night that fixed it.

**Pull request merged**
